# Generated by Django 5.2.7 on 2025-10-24 15:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_selected', models.CharField(blank=True, max_length=10)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('price_at_booking', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('instructor', models.CharField(max_length=15)),
                ('capacity_current', models.PositiveIntegerField(default=0)),
                ('capacity_max', models.PositiveIntegerField(default=20)),
                ('description', models.CharField(blank=True, max_length=60)),
                ('price', models.PositiveIntegerField()),
                ('room', models.CharField(max_length=5)),
                ('days', models.JSONField(blank=True, default=list)),
                ('time', models.CharField(choices=[('10.00 AM - 11.30 AM', '10.00 AM - 11.30 AM'), ('12.00 PM - 13.30 PM', '12.00 PM - 13.30 PM'), ('14.00 PM - 15.30 PM', '14.00 PM - 15.30 PM'), ('16.00 PM - 17.30 PM', '16.00 PM - 17.30 PM'), ('18.00 PM - 19.30 PM', '18.00 PM - 19.30 PM')], max_length=20)),
            ],
        ),
    ]
