# Generated by Django 5.2.7 on 2025-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingkelas', '0002_classoccurrence_booking_schedulerule'),
        ('checkout', '0002_remove_bookingorderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('instructor', models.CharField(max_length=100)),
                ('capacity_current', models.PositiveIntegerField(default=0)),
                ('capacity_max', models.PositiveIntegerField(default=20)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('room', models.CharField(max_length=100)),
                ('days', models.JSONField(blank=True, default=list)),
                ('time', models.CharField(choices=[('Afternoon', '14.00 PM  - 15.30 PM'), ('Noon', '16.00 PM - 17.30'), ('Evening', '18.00 PM - 19.30 PM')], max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classoccurrence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='schedulerule',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='ClassOccurrence',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
        migrations.DeleteModel(
            name='ScheduleRule',
        ),
    ]
