# Generated by Django 5.2.7 on 2025-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingkelas', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsessions',
            name='time',
            field=models.CharField(choices=[('Morning', '10.00 AM - 11.30 AM'), ('Midday', '12.00 PM - 13.30 PM'), ('Afternoon', '14.00 PM  - 15.30 PM'), ('Noon', '16.00 PM - 17.30'), ('Evening', '18.00 PM - 19.30 PM')], max_length=20),
        ),
    ]
