# Generated by Django 5.2.7 on 2025-10-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingkelas', '0006_alter_classsessions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsessions',
            name='description',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='classsessions',
            name='instructor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='classsessions',
            name='room',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='classsessions',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
