# Generated by Django 5.2.7 on 2025-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingkelas', '0007_alter_classsessions_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsessions',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
