# Generated by Django 5.2.7 on 2025-10-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingkelas', '0008_alter_classsessions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsessions',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
