# Generated by Django 5.2.7 on 2025-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingkelas', '0009_alter_classsessions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsessions',
            name='time',
            field=models.CharField(choices=[('10.00 AM - 11.30 AM', '10.00 AM - 11.30 AM'), ('12.00 PM - 13.30 PM', '12.00 PM - 13.30 PM'), ('14.00 PM - 15.30 PM', '14.00 PM - 15.30 PM'), ('16.00 PM - 17.30 PM', '16.00 PM - 17.30 PM'), ('18.00 PM - 19.30 PM', '18.00 PM - 19.30 PM')], max_length=20),
        ),
    ]
