# Generated by Django 5.2.7 on 2025-10-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='BookingOrder',
        ),
        migrations.DeleteModel(
            name='BookingOrderItem',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.DeleteModel(
            name='ProductOrderItem',
        ),
    ]
