# Generated by Django 5.2.7 on 2025-11-26 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookingkelas', '0002_initial'),
        ('cart', '0002_initial'),
        ('catalog', '0001_initial'),
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingorderitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='bookingkelas.booking'),
        ),
        migrations.AddField(
            model_name='bookingorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.bookingorder'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.productorder'),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='bookingorder',
            index=models.Index(fields=['user', 'created_at'], name='checkout_bo_user_id_a76e0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingorderitem',
            constraint=models.UniqueConstraint(fields=('booking',), name='unique_booking_per_order_items'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['user', 'created_at'], name='checkout_pr_user_id_27c63b_idx'),
        ),
    ]
