# Generated by Django 5.2.7 on 2025-12-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingkelas', '0002_initial'),
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorderitem',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='bookingkelas.booking'),
        ),
    ]
