# Generated by Django 5.2.7 on 2025-10-22 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('inStock', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
