# Generated by Django 5.2.7 on 2025-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID unik dari dataset/CSV (1 baris CSV = 1 produk).', max_length=64, null=True, unique=True),
        ),
    ]
