# Generated by Django 5.2.7 on 2025-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("user", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="wishlisted_by",
                to="catalog.product",
            ),
        ),
    ]
